#main program
import exceptions

exceptions.multiply_two_numbers()

